<a href="https://colab.research.google.com/github/arctron/learn-pytorch/blob/main/Learn_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Following the 60 min blitz tutorial at https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html

In [1]:
import torch
import numpy as np

In [2]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
print(type(data))
print(type(x_data))
print(x_data.dtype)
x_data

<class 'list'>
<class 'torch.Tensor'>
torch.int64


tensor([[1, 2],
        [3, 4]])

In [3]:
np_data = np.array(data)
x_np_data = torch.tensor(np_data)
print(type(np_data))
print(np_data.dtype)
print(np_data)
print(type(x_np_data))
print(x_np_data.dtype)
x_np_data

<class 'numpy.ndarray'>
int64
[[1 2]
 [3 4]]
<class 'torch.Tensor'>
torch.int64


tensor([[1, 2],
        [3, 4]])

In [4]:
x_ones = torch.ones_like(x_data)
print(x_ones.dtype, x_data.dtype)
print(x_ones.shape, x_data.shape)
print(x_ones)

torch.int64 torch.int64
torch.Size([2, 2]) torch.Size([2, 2])
tensor([[1, 1],
        [1, 1]])


In [5]:
x_rand = torch.rand_like(x_data, dtype=torch.float) # or torch.float32
print(x_rand.dtype)
print(x_rand)

x_rand = torch.rand_like(x_data, dtype=torch.double) # or torch.float64
print(x_rand.dtype)
print(x_rand)

torch.float32
tensor([[0.1852, 0.3954],
        [0.1142, 0.0138]])
torch.float64
tensor([[0.8419, 0.8691],
        [0.2019, 0.7582]], dtype=torch.float64)


In [6]:
shape = (2,3,)
x_zeros = torch.zeros(shape, dtype=torch.long) # torch.int64
print(x_zeros.dtype, x_zeros.shape, x_zeros.device)
print(x_zeros)

torch.int64 torch.Size([2, 3]) cpu
tensor([[0, 0, 0],
        [0, 0, 0]])


In [7]:
if torch.cuda.is_available():
  x_zeros = x_zeros.to('cuda')
  print(x_zeros.device) #'should be cuda'

cuda:0


In [8]:
tensor = torch.ones(4,4)
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [9]:
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [10]:
t1 = torch.cat([tensor, tensor, tensor], dim=0) # concat row wise
print(t1.shape)
print(t1)

t1 = torch.cat([tensor, tensor, tensor], dim=1) # concat column wise
print(t1.shape)
print(t1)

torch.Size([12, 4])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
torch.Size([4, 12])
tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [11]:
t1 = torch.rand((2,3))
t2 = torch.rand((2,3))

# Element wise multiplication
print(t1.mul(t2))
print(t1 * t2)

tensor([[4.8973e-02, 3.2673e-01, 2.3784e-01],
        [4.6950e-04, 6.4221e-02, 5.8784e-01]])
tensor([[4.8973e-02, 3.2673e-01, 2.3784e-01],
        [4.6950e-04, 6.4221e-02, 5.8784e-01]])


In [12]:
t1 = torch.rand((2,3))
t2 = torch.rand((3,5))

# Matrix multiplication
print(t1.matmul(t2))
print(t1 @ t2)

tensor([[1.3076, 1.3485, 1.6356, 0.9428, 0.4589],
        [0.9358, 0.9676, 1.2364, 0.5598, 0.2770]])
tensor([[1.3076, 1.3485, 1.6356, 0.9428, 0.4589],
        [0.9358, 0.9676, 1.2364, 0.5598, 0.2770]])


In [13]:
print(t1)
t1.add_(5) # in place op
print(t1)

tensor([[0.5734, 0.6241, 0.9249],
        [0.1650, 0.5559, 0.9025]])
tensor([[5.5734, 5.6241, 5.9249],
        [5.1650, 5.5559, 5.9025]])


In [14]:
t = torch.ones(5)
n = t.numpy() # shares same underlying mem on cpu
print(t)
print(n)

t.add_(4)

print(t)
print(n)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([5., 5., 5., 5., 5.])
[5. 5. 5. 5. 5.]


In [15]:
n = np.ones(7)
t = torch.from_numpy(n) # shares same underlying mem on cpu

print(n)
print(t)

np.add(n, 4, out=n)

print(n)
print(t)

[1. 1. 1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1., 1., 1.], dtype=torch.float64)
[5. 5. 5. 5. 5. 5. 5.]
tensor([5., 5., 5., 5., 5., 5., 5.], dtype=torch.float64)
