<a href="https://colab.research.google.com/github/arctron/learn-pytorch/blob/main/PyTorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Following tutorial at https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
import torch
torch.__version__

'2.0.1+cu118'

In [2]:
scalar = torch.tensor(7)
print(scalar)
print(scalar.shape)
print(scalar.dtype)
print(scalar.ndim)
print(scalar.item())

tensor(7)
torch.Size([])
torch.int64
0
7


In [3]:
vector = torch.tensor([7,7])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([7, 7])
1
torch.Size([2])


In [4]:
MATRIX = torch.tensor([[1,2], [3,4]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)

tensor([[1, 2],
        [3, 4]])
2
torch.Size([2, 2])


In [5]:
TENSOR = torch.tensor([[[1,2], [3,4]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)

tensor([[[1, 2],
         [3, 4]]])
3
torch.Size([1, 2, 2])


In [6]:
print(torch.rand(2,3))
print(torch.zeros(2,3))
print(torch.ones(2,3))

tensor([[0.6120, 0.1577, 0.9027],
        [0.5306, 0.6089, 0.6547]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [7]:
t1 = torch.arange(0, 10, 1)
print(t1)
print(t1.shape, t1.ndim, t1.dtype)
print(torch.zeros_like(t1))
print(torch.ones_like(t1))

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.Size([10]) 1 torch.int64
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [8]:
t2 = torch.tensor([1,2,3])
print(t2 + 10)
print(t2 - 10)
print(t2 * 10)
print(t2 / 10)
print(t2 ** 2)
print(-t2)
print(t2)

tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000])
tensor([1, 4, 9])
tensor([-1, -2, -3])
tensor([1, 2, 3])


In [9]:
t1 = torch.rand(2,3)
t2 = torch.rand(2,3)

t1 @ t2.T

tensor([[0.7202, 1.1864],
        [0.7813, 0.8216]])

In [10]:
torch.manual_seed(42)
m = torch.nn.Linear(2, 6)
print(m)
print(m.weight.shape, m.bias.shape)
x = torch.rand(3, 2)
out = m(x)
print(out)
print(out.shape)

print(x @ m.weight.T + m.bias)
print(torch.equal(out, x @ m.weight.T + m.bias))

Linear(in_features=2, out_features=6, bias=True)
torch.Size([6, 2]) torch.Size([6])
tensor([[ 1.0348,  0.4592,  0.3892,  0.0690,  0.3858,  0.3514],
        [ 0.9272,  0.3378,  0.3622, -0.0094,  0.4842,  0.3286],
        [ 1.1711,  0.5868,  0.4136,  0.1433,  0.2987,  0.3971]],
       grad_fn=<AddmmBackward0>)
torch.Size([3, 6])
tensor([[ 1.0348,  0.4592,  0.3892,  0.0690,  0.3858,  0.3514],
        [ 0.9272,  0.3378,  0.3622, -0.0094,  0.4842,  0.3286],
        [ 1.1711,  0.5868,  0.4136,  0.1433,  0.2987,  0.3971]],
       grad_fn=<AddBackward0>)
True


In [11]:
# Aggregation
x = torch.arange(0, 100, 10).type(torch.float)
print(x)
print(x.dtype, x.shape, x.device)
print(f'{x.min()=}')
print(f'{x.max()=}')
print(f'{x.type(torch.float).mean()=}')
print(f'{x.sum()=}')

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])
torch.float32 torch.Size([10]) cpu
x.min()=tensor(0.)
x.max()=tensor(90.)
x.type(torch.float).mean()=tensor(45.)
x.sum()=tensor(450.)


In [12]:
# Position of min/max
x = torch.tensor([1,2,3,0,2,1,0,3])
print(x)
print(f'Found min value {x.min()} at index {x.argmin()}')
print(f'Found max value {x.max()} at index {x.argmax()}')

tensor([1, 2, 3, 0, 2, 1, 0, 3])
Found min value 0 at index 3
Found max value 3 at index 2
